conversation_settings:
  participants:
    person_one:
      name: "Antonio"
      role: "main summarizer"
      language: "Spanish"
    person_two:
      name: "Claudia"
      role: "explainer and mediator"
      language: "Portuguese"
    person_three:
      name: "Maria"
      role: "questioner/clarifier"
      language: "Russian, French, Spanish"

conversation_style:
  - "engaging"
  - "fast-paced"
  - "enthusiastic"

dialogue_structure:
  - "Introduction"
  - "Main Content Summary"
  - "Conclusion"

podcast_name: "Quanta Intelligence"
podcast_tagline: "Your AI Podcast"
output_language: "English"

engagement_techniques:
  - "rhetorical questions"
  - "anecdotes"
  - "analogies"
  - "humor"

creativity: 1

conversation_flow:
  introduction:
    opening_statement: "Welcome to Quanta Intelligence - Your Personal GenAI Podcast."
    speakers: ["Antonio", "Claudia", "Maria"]
    structure:
      - Antonio: "Energetic greeting and introduction to the episode topic."
      - Maria: "Ground the conversation, expressing curiosity or skepticism."
      - Claudia: "Provide additional context or setup."

  discussion:
    topic_breakdown:
      segments:
        - "Key Points Analysis"
        - "Deep Dive into Relevant Themes"
      speaker_rotation: ["Antonio", "Claudia", "Maria"]
      interjections:
        Claudia: "Let me explain this in simpler terms."
        Maria: "That sounds questionable, can you elaborate?"
        Antonio: "Exactly! This is why it's so exciting!"

  conclusion:
    closing_remarks: "Thanks for listening to Quanta Intelligence - Your GenAI Podcast. We hope you enjoyed today's discussion."
    speaker_sequence: ["Antonio", "Claudia", "Maria"]
    final_statements:
      - Claudia: "Summarize key takeaways."
      - Maria: "Provide a skeptical viewpoint or reflective statement."
      - Antonio: "Energetic call-to-action for subscriptions and next episode."

speaker_properties:
  Antonio:
    tone: "Energetic"
    pace: "Fast"
  Maria:
    tone: "Skeptical"
    pace: "Measured"
  Claudia:
    tone: "Calm"
    pace: "Explanatory"

transitions:
  between_speakers:
    - "<break time=\"0.2s\" />"
  to_new_segment:
    - "Let's move on to our next point... <break time=\"0.3s\" />"

fallback_lines:
  Claudia: "Let me clarify this further for our listeners."
  Maria: "Hmm, I still have my doubts about this."
  Antonio: "Come on, it's obvious, isn’t it?"

text_to_speech:
  default_tts_model: "openai"
  elevenlabs:
    default_voices:
      question: "Antonio_v2"
      answer: "Maria"
      narrator: "Nadya"
    model: "eleven_multilingual_v2"
  openai:
    default_voices:
      question: "echo"
      answer: "shimmer"
      narrator: "nova"
    model: "tts-1-hd"
  edge:
    default_voices:
      question: "en-US-JennyNeural"
      answer: "en-US-EricNeural"
      narrator: "en-US-GuyNeural"
  audio_format: "mp3"
  temp_audio_dir: "data/audio/tmp/"
  ending_message: "Bye Bye!"
