word_count: 2000
conversation_style: 
  - "engaging"
  - "fast-paced"
  - "enthusiastic"
roles_person1: "main summarizer"
roles_person2: "questioner/clarifier"
roles_person3: "contributor/analyst"
dialogue_structure: 
  - "Introduction"
  - "Main Content Summary"
  - "Conclusion"
podcast_name: "Quanta Intelligence"
podcast_tagline: "Your Personal Generative AI Podcast"
output_language: "English"
engagement_techniques: 
  - "rhetorical questions"
  - "anecdotes"
  - "analogies"
  - "humor"
creativity: 1

text_to_speech:
  default_tts_model: "openai"
  elevenlabs:
    default_voices:
      question: "ULaD4kyEFZX66G2Yjc8P"
      answer: "yu4eXTP5aod8KAQzTI3T"
      analysis: "bZZtMxNj5msNa8oBkE7V"
    model: "eleven_multilingual_v2"
  openai:
    default_voices:
      question: "echo"
      answer: "shimmer"
      analysis: "onyx"
    model: "tts-1-hd"
  edge:
    default_voices:
      question: "en-US-JennyNeural"
      answer: "en-US-EricNeural"
      analysis: "en-US-GuyNeural"
  audio_format: "mp3"
  temp_audio_dir: "data/audio/tmp/"
  ending_message: "Bye Bye!"
